//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBClientProject.RadarDB {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Radar", Namespace="http://schemas.datacontract.org/2004/07/DBService")]
    [System.SerializableAttribute()]
    public partial class Radar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DopuszczlnaPredkoscField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> KierunekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazwaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WlascicielField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> XField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> YField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DopuszczlnaPredkosc {
            get {
                return this.DopuszczlnaPredkoscField;
            }
            set {
                if ((this.DopuszczlnaPredkoscField.Equals(value) != true)) {
                    this.DopuszczlnaPredkoscField = value;
                    this.RaisePropertyChanged("DopuszczlnaPredkosc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Kierunek {
            get {
                return this.KierunekField;
            }
            set {
                if ((this.KierunekField.Equals(value) != true)) {
                    this.KierunekField = value;
                    this.RaisePropertyChanged("Kierunek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwa {
            get {
                return this.NazwaField;
            }
            set {
                if ((object.ReferenceEquals(this.NazwaField, value) != true)) {
                    this.NazwaField = value;
                    this.RaisePropertyChanged("Nazwa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Wlasciciel {
            get {
                return this.WlascicielField;
            }
            set {
                if ((object.ReferenceEquals(this.WlascicielField, value) != true)) {
                    this.WlascicielField = value;
                    this.RaisePropertyChanged("Wlasciciel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> X {
            get {
                return this.XField;
            }
            set {
                if ((this.XField.Equals(value) != true)) {
                    this.XField = value;
                    this.RaisePropertyChanged("X");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Y {
            get {
                return this.YField;
            }
            set {
                if ((this.YField.Equals(value) != true)) {
                    this.YField = value;
                    this.RaisePropertyChanged("Y");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Token", Namespace="http://schemas.datacontract.org/2004/07/DBService")]
    [System.SerializableAttribute()]
    public partial class Token : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentEditorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EditGrantedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentEditor {
            get {
                return this.CurrentEditorField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentEditorField, value) != true)) {
                    this.CurrentEditorField = value;
                    this.RaisePropertyChanged("CurrentEditor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EditGranted {
            get {
                return this.EditGrantedField;
            }
            set {
                if ((this.EditGrantedField.Equals(value) != true)) {
                    this.EditGrantedField = value;
                    this.RaisePropertyChanged("EditGranted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenValue {
            get {
                return this.TokenValueField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenValueField, value) != true)) {
                    this.TokenValueField = value;
                    this.RaisePropertyChanged("TokenValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RadarDB.IRadarService")]
    public interface IRadarService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRadarService/GetRadarList", ReplyAction="http://tempuri.org/IRadarService/GetRadarListResponse")]
        DBClientProject.RadarDB.Radar[] GetRadarList(string nameFilter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRadarService/GetRadarList", ReplyAction="http://tempuri.org/IRadarService/GetRadarListResponse")]
        System.Threading.Tasks.Task<DBClientProject.RadarDB.Radar[]> GetRadarListAsync(string nameFilter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRadarService/GetEditToken", ReplyAction="http://tempuri.org/IRadarService/GetEditTokenResponse")]
        DBClientProject.RadarDB.Token GetEditToken(int id, string tableName, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRadarService/GetEditToken", ReplyAction="http://tempuri.org/IRadarService/GetEditTokenResponse")]
        System.Threading.Tasks.Task<DBClientProject.RadarDB.Token> GetEditTokenAsync(int id, string tableName, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRadarService/EditRadar", ReplyAction="http://tempuri.org/IRadarService/EditRadarResponse")]
        bool EditRadar(string token, DBClientProject.RadarDB.Radar radar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRadarService/EditRadar", ReplyAction="http://tempuri.org/IRadarService/EditRadarResponse")]
        System.Threading.Tasks.Task<bool> EditRadarAsync(string token, DBClientProject.RadarDB.Radar radar);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRadarServiceChannel : DBClientProject.RadarDB.IRadarService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RadarServiceClient : System.ServiceModel.ClientBase<DBClientProject.RadarDB.IRadarService>, DBClientProject.RadarDB.IRadarService {
        
        public RadarServiceClient() {
        }
        
        public RadarServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RadarServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RadarServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RadarServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DBClientProject.RadarDB.Radar[] GetRadarList(string nameFilter) {
            return base.Channel.GetRadarList(nameFilter);
        }
        
        public System.Threading.Tasks.Task<DBClientProject.RadarDB.Radar[]> GetRadarListAsync(string nameFilter) {
            return base.Channel.GetRadarListAsync(nameFilter);
        }
        
        public DBClientProject.RadarDB.Token GetEditToken(int id, string tableName, string UserName) {
            return base.Channel.GetEditToken(id, tableName, UserName);
        }
        
        public System.Threading.Tasks.Task<DBClientProject.RadarDB.Token> GetEditTokenAsync(int id, string tableName, string UserName) {
            return base.Channel.GetEditTokenAsync(id, tableName, UserName);
        }
        
        public bool EditRadar(string token, DBClientProject.RadarDB.Radar radar) {
            return base.Channel.EditRadar(token, radar);
        }
        
        public System.Threading.Tasks.Task<bool> EditRadarAsync(string token, DBClientProject.RadarDB.Radar radar) {
            return base.Channel.EditRadarAsync(token, radar);
        }
    }
}
